FROM python:3.11-slim

WORKDIR /app
COPY . /app
ENV SERVICEPILOT_HOST=0.0.0.0 \
    SERVICEPILOT_PORT=8770 \
    ENABLE_OLLAMA=0 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
EXPOSE 8770
CMD ["python", "app.py"]
